/**
 * Emitters: turn token data into CSS custom properties and Sass.
 *
 * - One theme file per preset (`dist/themes/<name>.css`): colors, fonts,
 *   radius, shadows for light + dark. Swapping themes = swapping one file.
 * - One generated Sass partial: breakpoint maps (media queries can't read
 *   custom properties) and the preset-independent scales.
 */

import { withAlpha, type Hex } from "./color.ts";
import type { Preset } from "./presets.ts";
import { SEMANTIC_COLOR_NAMES, type Mode, type SemanticColors } from "./semantics.ts";
import {
  breakpoints,
  containers,
  fontSize,
  fontWeight,
  lineHeight,
  misc,
  motion,
  radiusStyles,
  space,
  tracking,
  zIndex,
} from "./scales.ts";

const decl = (name: string, value: string) => `  --sb-${name}: ${value};`;

function colorDecls(colors: SemanticColors): string[] {
  return Object.entries(colors).map(([name, value]) => decl(name, value));
}

function shadowDecls(mode: Mode, tint: Hex): string[] {
  const t = (a: number) => withAlpha(mode === "light" ? tint : "#000000", mode === "light" ? a : Math.min(a * 2.4, 0.7));
  return [
    decl("shadow-xs", `0 1px 2px ${t(0.06)}`),
    decl("shadow-sm", `0 1px 3px ${t(0.09)}, 0 1px 2px ${t(0.05)}`),
    decl("shadow-md", `0 4px 10px -2px ${t(0.12)}, 0 2px 4px -2px ${t(0.06)}`),
    decl("shadow-lg", `0 12px 24px -6px ${t(0.16)}, 0 4px 8px -4px ${t(0.06)}`),
    decl("shadow-xl", `0 24px 48px -12px ${t(0.24)}`),
  ];
}

function modeBlock(preset: Preset, mode: Mode): string[] {
  return [`  color-scheme: ${mode};`, ...colorDecls(preset.colors[mode]), ...shadowDecls(mode, preset.shadowTint)];
}

export function themeCss(preset: Preset): string {
  const radius = radiusStyles[preset.radiusStyle];
  const dark = modeBlock(preset, "dark").join("\n");

  return `/* Sorbet DS theme: ${preset.name} — ${preset.tagline}
 * GENERATED by \`npm run build:tokens\` — edit src/tokens/, not this file. */

:root {
${decl("font-sans", preset.fonts.sans)}
${decl("font-display", preset.fonts.display)}
${decl("font-mono", preset.fonts.mono)}
${Object.entries(radius)
  .map(([k, v]) => decl(`radius-${k}`, v))
  .join("\n")}
${decl("radius-full", "999px")}
${modeBlock(preset, "light").join("\n")}
}

/* Explicit opt-in: <html data-theme="dark"> */
[data-theme="dark"] {
${dark}
}

/* System preference, unless the page opted out with data-theme="light" */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${dark}
  }
}
`;
}

const group = (obj: Record<string, string>, prefix: string) =>
  Object.entries(obj).map(([k, v]) => decl(prefix ? `${prefix}-${k}` : k, v));

export function generatedScss(): string {
  const mapEntries = (obj: Record<string, string>) =>
    Object.entries(obj)
      .map(([k, v]) => `  ${JSON.stringify(k)}: ${v},`)
      .join("\n");

  const list = (items: readonly string[]) => items.map((i) => JSON.stringify(i)).join(", ");
  const strip = (obj: Record<string, string>, prefix: string) =>
    Object.keys(obj).map((k) => k.replace(`${prefix}-`, ""));

  return `// GENERATED by \`npm run build:tokens\` — edit src/tokens/scales.ts, not this file.
// Breakpoints live in Sass because media queries cannot read custom properties.

$breakpoints: (
${mapEntries(breakpoints)}
);

$containers: (
${mapEntries(containers)}
);

// Known token names — the abstracts validate against these at compile time,
// so a typo'd token is a build error instead of a silently-broken var().
$semantic-colors: (${list(SEMANTIC_COLOR_NAMES)});

$scale-keys: (
  "space": (${list(Object.keys(space))}),
  "text": (${list(Object.keys(fontSize))}),
  "leading": (${list(Object.keys(lineHeight))}),
  "weight": (${list(Object.keys(fontWeight))}),
  "tracking": (${list(Object.keys(tracking))}),
  "radius": ("xs", "sm", "md", "lg", "xl", "full"),
  "shadow": ("xs", "sm", "md", "lg", "xl"),
  "duration": (${list(strip(motion, "duration").filter((k) => !k.startsWith("ease")))}),
  "ease": (${list(strip(motion, "ease").filter((k) => !k.startsWith("duration")))}),
  "z": (${list(strip(zIndex, "z"))}),
  "font": ("sans", "display", "mono"),
);

// Preset-independent tokens, emitted once from base/_root.scss.
@mixin static-tokens {
${[
  ...group(space, "space"),
  ...group(fontSize, "text"),
  ...group(lineHeight, "leading"),
  ...group(fontWeight, "weight"),
  ...group(tracking, "tracking"),
  ...group(motion, ""),
  ...group(zIndex, ""),
  ...group(misc, ""),
].join("\n")}
}
`;
}

export function manifest(all: Record<string, Preset>): string {
  return JSON.stringify(
    Object.values(all).map(({ name, label, tagline, defaultMode, radiusStyle }) => ({
      name,
      label,
      tagline,
      defaultMode,
      radiusStyle,
    })),
    null,
    2,
  );
}
