#!/usr/bin/env python3
"""Regenerate reference/*.md from the Sass partials.

The reference tables are DERIVED data — every block class and modifier that
actually compiles. Hand-maintaining them guarantees they drift, and a stale
class map is worse than none: it makes the agent apply classes that no longer
exist. Run this after adding or renaming a component.

    python3 .claude/skills/sorbet-classes/refresh.py
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(
    subprocess.run(
        ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=True
    ).stdout.strip()
)
STYLES = ROOT / "packages/design-system/src/styles"
OUT = ROOT / ".claude/skills/sorbet-classes/reference"

GROUPS = {
    "atoms": ["atoms"],
    "molecules-organisms": ["molecules", "organisms"],
    "layout": ["layout"],
}


def blocks_for(layer: str) -> dict[str, tuple[str, list[str]]]:
    """{block class: (partial filename, [modifiers])} for one layer directory."""
    found: dict[str, tuple[str, list[str]]] = {}
    directory = STYLES / layer
    if not directory.is_dir():
        return found
    for partial in sorted(directory.glob("*.scss")):
        current = None
        for match in re.finditer(r"^\.(sb-[a-z0-9-]+)|&--([a-z0-9-]+)", partial.read_text(), re.M):
            block, modifier = match.group(1), match.group(2)
            if block:
                current = block
                found.setdefault(current, (partial.name, []))
            elif current and modifier not in found[current][1]:
                found[current][1].append(modifier)
    return found


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    total = 0
    for name, layers in GROUPS.items():
        lines = [
            f"# `{name}` classes",
            "",
            "Generated by `refresh.py` — do not hand-edit. Every block below compiles;",
            "anything not listed here does not exist.",
            "",
        ]
        for layer in layers:
            found = blocks_for(layer)
            total += len(found)
            lines += [f"## {layer}", "", "| class | modifiers | partial |", "| --- | --- | --- |"]
            for block, (partial, modifiers) in sorted(found.items()):
                mods = " ".join(f"`--{m}`" for m in sorted(modifiers)) or "—"
                lines.append(f"| `.{block}` | {mods} | `{layer}/{partial}` |")
            lines.append("")
        (OUT / f"{name}.md").write_text("\n".join(lines))
        print(f"  wrote reference/{name}.md")
    print(f"  {total} block classes total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
